name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*

env:
  IMAGE_NAME: sun-panel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码库
        uses: actions/checkout@v3

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 构建并推送镜像
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: woodchen/${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            VERSION=latest
          username: woodchen
          password: ${{ secrets.ACCESS_TOKEN }}
